package info.bicoin.credit.entity;

import java.math.BigDecimal;
import java.util.Date;

/**
 * blz user
 */
public class User {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.id
     *
     * @mbg.generated
     */
    private Long id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.nick_name
     *
     * @mbg.generated
     */
    private String nickName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.password
     *
     * @mbg.generated
     */
    private String password;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.email
     *
     * @mbg.generated
     */
    private String email;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.phone
     *
     * @mbg.generated
     */
    private String phone;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.avatar
     *
     * @mbg.generated
     */
    private String avatar;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.brief
     *
     * @mbg.generated
     */
    private String brief;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.invite_code
     *
     * @mbg.generated
     */
    private String inviteCode;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.score
     *
     * @mbg.generated
     */
    private Integer score;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.gold
     *
     * @mbg.generated
     */
    private Integer gold;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.c_time
     *
     * @mbg.generated
     */
    private Date cTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.u_time
     *
     * @mbg.generated
     */
    private Date uTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.wx_push
     *
     * @mbg.generated
     */
    private Boolean wxPush;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.wx_night_push
     *
     * @mbg.generated
     */
    private Boolean wxNightPush;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.price_remind_type
     *
     * @mbg.generated
     */
    private Integer priceRemindType;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.price_wave_remind_type
     *
     * @mbg.generated
     */
    private Integer priceWaveRemindType;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.big_amount_remind_type
     *
     * @mbg.generated
     */
    private Integer bigAmountRemindType;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.notice_remind_type
     *
     * @mbg.generated
     */
    private Integer noticeRemindType;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.big_order_remind_type
     *
     * @mbg.generated
     */
    private Integer bigOrderRemindType;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.circle_remind_type
     *
     * @mbg.generated
     */
    private Integer circleRemindType;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.is_accept_project_remind
     *
     * @mbg.generated
     */
    private Boolean isAcceptProjectRemind;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.out_of_stock_remind_type
     *
     * @mbg.generated
     */
    private Integer outOfStockRemindType;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.mobil_id
     *
     * @mbg.generated
     */
    private String mobilId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.user_temp_flag
     *
     * @mbg.generated
     */
    private Boolean userTempFlag;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.flow_any_ratio
     *
     * @mbg.generated
     */
    private BigDecimal flowAnyRatio;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.flow_in_ratio
     *
     * @mbg.generated
     */
    private BigDecimal flowInRatio;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.flow_out_ratio
     *
     * @mbg.generated
     */
    private BigDecimal flowOutRatio;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.notice_idea
     *
     * @mbg.generated
     */
    private Integer noticeIdea;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.high_low_remind_type
     *
     * @mbg.generated
     */
    private Integer highLowRemindType;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.is_boll_send_type
     *
     * @mbg.generated
     */
    private Integer isBollSendType;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.is_kdj_send_type
     *
     * @mbg.generated
     */
    private Integer isKdjSendType;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.invite_count
     *
     * @mbg.generated
     */
    private Integer inviteCount;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.active_invite_count
     *
     * @mbg.generated
     */
    private Integer activeInviteCount;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.used_active_invite_count
     *
     * @mbg.generated
     */
    private Integer usedActiveInviteCount;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.is_firm_vip
     *
     * @mbg.generated
     */
    private Integer isFirmVip;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.is_firm offer
     *
     * @mbg.generated
     */
    private Integer isFirmOffer;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.is_eth_report
     *
     * @mbg.generated
     */
    private Integer isEthReport;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.system_type
     *
     * @mbg.generated
     */
    private Integer systemType;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.boll_switch
     *
     * @mbg.generated
     */
    private Boolean bollSwitch;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.kdj_swich
     *
     * @mbg.generated
     */
    private Boolean kdjSwich;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.big_order_swich
     *
     * @mbg.generated
     */
    private Boolean bigOrderSwich;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.price_wave_swich
     *
     * @mbg.generated
     */
    private Boolean priceWaveSwich;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.login_time
     *
     * @mbg.generated
     */
    private Long loginTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.transaction_report_remind_type
     *
     * @mbg.generated
     */
    private Integer transactionReportRemindType;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.hasMarketIndex
     *
     * @mbg.generated
     */
    private String hasmarketindex;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.invite_code_discount_count_all
     *
     * @mbg.generated
     */
    private Integer inviteCodeDiscountCountAll;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.invite_code_discount_count_use
     *
     * @mbg.generated
     */
    private Integer inviteCodeDiscountCountUse;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.lucky_draw_count
     *
     * @mbg.generated
     */
    private Integer luckyDrawCount;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.breakout_qdisk_type
     *
     * @mbg.generated
     */
    private Integer breakoutQdiskType;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.stock_begin_type
     *
     * @mbg.generated
     */
    private Integer stockBeginType;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.is_firm_offer_type
     *
     * @mbg.generated
     */
    private Integer isFirmOfferType;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.sign_in_days
     *
     * @mbg.generated
     */
    private Integer signInDays;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.is_half_stock_type
     *
     * @mbg.generated
     */
    private Integer isHalfStockType;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.is_start_stock_type
     *
     * @mbg.generated
     */
    private Integer isStartStockType;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.area_code
     *
     * @mbg.generated
     */
    private String areaCode;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.call_count
     *
     * @mbg.generated
     */
    private Integer callCount;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.okex_api_status
     *
     * @mbg.generated
     */
    private Boolean okexApiStatus;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.bitmex_api_status
     *
     * @mbg.generated
     */
    private Boolean bitmexApiStatus;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.is_big_v
     *
     * @mbg.generated
     */
    private Boolean isBigV;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.leader_id
     *
     * @mbg.generated
     */
    private Long leaderId;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.id
     *
     * @return the value of user.id
     *
     * @mbg.generated
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.id
     *
     * @param id the value for user.id
     *
     * @mbg.generated
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.nick_name
     *
     * @return the value of user.nick_name
     *
     * @mbg.generated
     */
    public String getNickName() {
        return nickName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.nick_name
     *
     * @param nickName the value for user.nick_name
     *
     * @mbg.generated
     */
    public void setNickName(String nickName) {
        this.nickName = nickName == null ? null : nickName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.password
     *
     * @return the value of user.password
     *
     * @mbg.generated
     */
    public String getPassword() {
        return password;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.password
     *
     * @param password the value for user.password
     *
     * @mbg.generated
     */
    public void setPassword(String password) {
        this.password = password == null ? null : password.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.email
     *
     * @return the value of user.email
     *
     * @mbg.generated
     */
    public String getEmail() {
        return email;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.email
     *
     * @param email the value for user.email
     *
     * @mbg.generated
     */
    public void setEmail(String email) {
        this.email = email == null ? null : email.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.phone
     *
     * @return the value of user.phone
     *
     * @mbg.generated
     */
    public String getPhone() {
        return phone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.phone
     *
     * @param phone the value for user.phone
     *
     * @mbg.generated
     */
    public void setPhone(String phone) {
        this.phone = phone == null ? null : phone.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.avatar
     *
     * @return the value of user.avatar
     *
     * @mbg.generated
     */
    public String getAvatar() {
        return avatar;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.avatar
     *
     * @param avatar the value for user.avatar
     *
     * @mbg.generated
     */
    public void setAvatar(String avatar) {
        this.avatar = avatar == null ? null : avatar.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.brief
     *
     * @return the value of user.brief
     *
     * @mbg.generated
     */
    public String getBrief() {
        return brief;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.brief
     *
     * @param brief the value for user.brief
     *
     * @mbg.generated
     */
    public void setBrief(String brief) {
        this.brief = brief == null ? null : brief.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.invite_code
     *
     * @return the value of user.invite_code
     *
     * @mbg.generated
     */
    public String getInviteCode() {
        return inviteCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.invite_code
     *
     * @param inviteCode the value for user.invite_code
     *
     * @mbg.generated
     */
    public void setInviteCode(String inviteCode) {
        this.inviteCode = inviteCode == null ? null : inviteCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.score
     *
     * @return the value of user.score
     *
     * @mbg.generated
     */
    public Integer getScore() {
        return score;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.score
     *
     * @param score the value for user.score
     *
     * @mbg.generated
     */
    public void setScore(Integer score) {
        this.score = score;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.gold
     *
     * @return the value of user.gold
     *
     * @mbg.generated
     */
    public Integer getGold() {
        return gold;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.gold
     *
     * @param gold the value for user.gold
     *
     * @mbg.generated
     */
    public void setGold(Integer gold) {
        this.gold = gold;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.c_time
     *
     * @return the value of user.c_time
     *
     * @mbg.generated
     */
    public Date getcTime() {
        return cTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.c_time
     *
     * @param cTime the value for user.c_time
     *
     * @mbg.generated
     */
    public void setcTime(Date cTime) {
        this.cTime = cTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.u_time
     *
     * @return the value of user.u_time
     *
     * @mbg.generated
     */
    public Date getuTime() {
        return uTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.u_time
     *
     * @param uTime the value for user.u_time
     *
     * @mbg.generated
     */
    public void setuTime(Date uTime) {
        this.uTime = uTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.wx_push
     *
     * @return the value of user.wx_push
     *
     * @mbg.generated
     */
    public Boolean getWxPush() {
        return wxPush;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.wx_push
     *
     * @param wxPush the value for user.wx_push
     *
     * @mbg.generated
     */
    public void setWxPush(Boolean wxPush) {
        this.wxPush = wxPush;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.wx_night_push
     *
     * @return the value of user.wx_night_push
     *
     * @mbg.generated
     */
    public Boolean getWxNightPush() {
        return wxNightPush;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.wx_night_push
     *
     * @param wxNightPush the value for user.wx_night_push
     *
     * @mbg.generated
     */
    public void setWxNightPush(Boolean wxNightPush) {
        this.wxNightPush = wxNightPush;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.price_remind_type
     *
     * @return the value of user.price_remind_type
     *
     * @mbg.generated
     */
    public Integer getPriceRemindType() {
        return priceRemindType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.price_remind_type
     *
     * @param priceRemindType the value for user.price_remind_type
     *
     * @mbg.generated
     */
    public void setPriceRemindType(Integer priceRemindType) {
        this.priceRemindType = priceRemindType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.price_wave_remind_type
     *
     * @return the value of user.price_wave_remind_type
     *
     * @mbg.generated
     */
    public Integer getPriceWaveRemindType() {
        return priceWaveRemindType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.price_wave_remind_type
     *
     * @param priceWaveRemindType the value for user.price_wave_remind_type
     *
     * @mbg.generated
     */
    public void setPriceWaveRemindType(Integer priceWaveRemindType) {
        this.priceWaveRemindType = priceWaveRemindType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.big_amount_remind_type
     *
     * @return the value of user.big_amount_remind_type
     *
     * @mbg.generated
     */
    public Integer getBigAmountRemindType() {
        return bigAmountRemindType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.big_amount_remind_type
     *
     * @param bigAmountRemindType the value for user.big_amount_remind_type
     *
     * @mbg.generated
     */
    public void setBigAmountRemindType(Integer bigAmountRemindType) {
        this.bigAmountRemindType = bigAmountRemindType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.notice_remind_type
     *
     * @return the value of user.notice_remind_type
     *
     * @mbg.generated
     */
    public Integer getNoticeRemindType() {
        return noticeRemindType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.notice_remind_type
     *
     * @param noticeRemindType the value for user.notice_remind_type
     *
     * @mbg.generated
     */
    public void setNoticeRemindType(Integer noticeRemindType) {
        this.noticeRemindType = noticeRemindType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.big_order_remind_type
     *
     * @return the value of user.big_order_remind_type
     *
     * @mbg.generated
     */
    public Integer getBigOrderRemindType() {
        return bigOrderRemindType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.big_order_remind_type
     *
     * @param bigOrderRemindType the value for user.big_order_remind_type
     *
     * @mbg.generated
     */
    public void setBigOrderRemindType(Integer bigOrderRemindType) {
        this.bigOrderRemindType = bigOrderRemindType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.circle_remind_type
     *
     * @return the value of user.circle_remind_type
     *
     * @mbg.generated
     */
    public Integer getCircleRemindType() {
        return circleRemindType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.circle_remind_type
     *
     * @param circleRemindType the value for user.circle_remind_type
     *
     * @mbg.generated
     */
    public void setCircleRemindType(Integer circleRemindType) {
        this.circleRemindType = circleRemindType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.is_accept_project_remind
     *
     * @return the value of user.is_accept_project_remind
     *
     * @mbg.generated
     */
    public Boolean getIsAcceptProjectRemind() {
        return isAcceptProjectRemind;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.is_accept_project_remind
     *
     * @param isAcceptProjectRemind the value for user.is_accept_project_remind
     *
     * @mbg.generated
     */
    public void setIsAcceptProjectRemind(Boolean isAcceptProjectRemind) {
        this.isAcceptProjectRemind = isAcceptProjectRemind;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.out_of_stock_remind_type
     *
     * @return the value of user.out_of_stock_remind_type
     *
     * @mbg.generated
     */
    public Integer getOutOfStockRemindType() {
        return outOfStockRemindType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.out_of_stock_remind_type
     *
     * @param outOfStockRemindType the value for user.out_of_stock_remind_type
     *
     * @mbg.generated
     */
    public void setOutOfStockRemindType(Integer outOfStockRemindType) {
        this.outOfStockRemindType = outOfStockRemindType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.mobil_id
     *
     * @return the value of user.mobil_id
     *
     * @mbg.generated
     */
    public String getMobilId() {
        return mobilId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.mobil_id
     *
     * @param mobilId the value for user.mobil_id
     *
     * @mbg.generated
     */
    public void setMobilId(String mobilId) {
        this.mobilId = mobilId == null ? null : mobilId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.user_temp_flag
     *
     * @return the value of user.user_temp_flag
     *
     * @mbg.generated
     */
    public Boolean getUserTempFlag() {
        return userTempFlag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.user_temp_flag
     *
     * @param userTempFlag the value for user.user_temp_flag
     *
     * @mbg.generated
     */
    public void setUserTempFlag(Boolean userTempFlag) {
        this.userTempFlag = userTempFlag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.flow_any_ratio
     *
     * @return the value of user.flow_any_ratio
     *
     * @mbg.generated
     */
    public BigDecimal getFlowAnyRatio() {
        return flowAnyRatio;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.flow_any_ratio
     *
     * @param flowAnyRatio the value for user.flow_any_ratio
     *
     * @mbg.generated
     */
    public void setFlowAnyRatio(BigDecimal flowAnyRatio) {
        this.flowAnyRatio = flowAnyRatio;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.flow_in_ratio
     *
     * @return the value of user.flow_in_ratio
     *
     * @mbg.generated
     */
    public BigDecimal getFlowInRatio() {
        return flowInRatio;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.flow_in_ratio
     *
     * @param flowInRatio the value for user.flow_in_ratio
     *
     * @mbg.generated
     */
    public void setFlowInRatio(BigDecimal flowInRatio) {
        this.flowInRatio = flowInRatio;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.flow_out_ratio
     *
     * @return the value of user.flow_out_ratio
     *
     * @mbg.generated
     */
    public BigDecimal getFlowOutRatio() {
        return flowOutRatio;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.flow_out_ratio
     *
     * @param flowOutRatio the value for user.flow_out_ratio
     *
     * @mbg.generated
     */
    public void setFlowOutRatio(BigDecimal flowOutRatio) {
        this.flowOutRatio = flowOutRatio;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.notice_idea
     *
     * @return the value of user.notice_idea
     *
     * @mbg.generated
     */
    public Integer getNoticeIdea() {
        return noticeIdea;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.notice_idea
     *
     * @param noticeIdea the value for user.notice_idea
     *
     * @mbg.generated
     */
    public void setNoticeIdea(Integer noticeIdea) {
        this.noticeIdea = noticeIdea;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.high_low_remind_type
     *
     * @return the value of user.high_low_remind_type
     *
     * @mbg.generated
     */
    public Integer getHighLowRemindType() {
        return highLowRemindType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.high_low_remind_type
     *
     * @param highLowRemindType the value for user.high_low_remind_type
     *
     * @mbg.generated
     */
    public void setHighLowRemindType(Integer highLowRemindType) {
        this.highLowRemindType = highLowRemindType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.is_boll_send_type
     *
     * @return the value of user.is_boll_send_type
     *
     * @mbg.generated
     */
    public Integer getIsBollSendType() {
        return isBollSendType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.is_boll_send_type
     *
     * @param isBollSendType the value for user.is_boll_send_type
     *
     * @mbg.generated
     */
    public void setIsBollSendType(Integer isBollSendType) {
        this.isBollSendType = isBollSendType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.is_kdj_send_type
     *
     * @return the value of user.is_kdj_send_type
     *
     * @mbg.generated
     */
    public Integer getIsKdjSendType() {
        return isKdjSendType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.is_kdj_send_type
     *
     * @param isKdjSendType the value for user.is_kdj_send_type
     *
     * @mbg.generated
     */
    public void setIsKdjSendType(Integer isKdjSendType) {
        this.isKdjSendType = isKdjSendType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.invite_count
     *
     * @return the value of user.invite_count
     *
     * @mbg.generated
     */
    public Integer getInviteCount() {
        return inviteCount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.invite_count
     *
     * @param inviteCount the value for user.invite_count
     *
     * @mbg.generated
     */
    public void setInviteCount(Integer inviteCount) {
        this.inviteCount = inviteCount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.active_invite_count
     *
     * @return the value of user.active_invite_count
     *
     * @mbg.generated
     */
    public Integer getActiveInviteCount() {
        return activeInviteCount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.active_invite_count
     *
     * @param activeInviteCount the value for user.active_invite_count
     *
     * @mbg.generated
     */
    public void setActiveInviteCount(Integer activeInviteCount) {
        this.activeInviteCount = activeInviteCount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.used_active_invite_count
     *
     * @return the value of user.used_active_invite_count
     *
     * @mbg.generated
     */
    public Integer getUsedActiveInviteCount() {
        return usedActiveInviteCount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.used_active_invite_count
     *
     * @param usedActiveInviteCount the value for user.used_active_invite_count
     *
     * @mbg.generated
     */
    public void setUsedActiveInviteCount(Integer usedActiveInviteCount) {
        this.usedActiveInviteCount = usedActiveInviteCount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.is_firm_vip
     *
     * @return the value of user.is_firm_vip
     *
     * @mbg.generated
     */
    public Integer getIsFirmVip() {
        return isFirmVip;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.is_firm_vip
     *
     * @param isFirmVip the value for user.is_firm_vip
     *
     * @mbg.generated
     */
    public void setIsFirmVip(Integer isFirmVip) {
        this.isFirmVip = isFirmVip;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.is_firm offer
     *
     * @return the value of user.is_firm offer
     *
     * @mbg.generated
     */
    public Integer getIsFirmOffer() {
        return isFirmOffer;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.is_firm offer
     *
     * @param isFirmOffer the value for user.is_firm offer
     *
     * @mbg.generated
     */
    public void setIsFirmOffer(Integer isFirmOffer) {
        this.isFirmOffer = isFirmOffer;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.is_eth_report
     *
     * @return the value of user.is_eth_report
     *
     * @mbg.generated
     */
    public Integer getIsEthReport() {
        return isEthReport;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.is_eth_report
     *
     * @param isEthReport the value for user.is_eth_report
     *
     * @mbg.generated
     */
    public void setIsEthReport(Integer isEthReport) {
        this.isEthReport = isEthReport;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.system_type
     *
     * @return the value of user.system_type
     *
     * @mbg.generated
     */
    public Integer getSystemType() {
        return systemType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.system_type
     *
     * @param systemType the value for user.system_type
     *
     * @mbg.generated
     */
    public void setSystemType(Integer systemType) {
        this.systemType = systemType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.boll_switch
     *
     * @return the value of user.boll_switch
     *
     * @mbg.generated
     */
    public Boolean getBollSwitch() {
        return bollSwitch;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.boll_switch
     *
     * @param bollSwitch the value for user.boll_switch
     *
     * @mbg.generated
     */
    public void setBollSwitch(Boolean bollSwitch) {
        this.bollSwitch = bollSwitch;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.kdj_swich
     *
     * @return the value of user.kdj_swich
     *
     * @mbg.generated
     */
    public Boolean getKdjSwich() {
        return kdjSwich;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.kdj_swich
     *
     * @param kdjSwich the value for user.kdj_swich
     *
     * @mbg.generated
     */
    public void setKdjSwich(Boolean kdjSwich) {
        this.kdjSwich = kdjSwich;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.big_order_swich
     *
     * @return the value of user.big_order_swich
     *
     * @mbg.generated
     */
    public Boolean getBigOrderSwich() {
        return bigOrderSwich;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.big_order_swich
     *
     * @param bigOrderSwich the value for user.big_order_swich
     *
     * @mbg.generated
     */
    public void setBigOrderSwich(Boolean bigOrderSwich) {
        this.bigOrderSwich = bigOrderSwich;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.price_wave_swich
     *
     * @return the value of user.price_wave_swich
     *
     * @mbg.generated
     */
    public Boolean getPriceWaveSwich() {
        return priceWaveSwich;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.price_wave_swich
     *
     * @param priceWaveSwich the value for user.price_wave_swich
     *
     * @mbg.generated
     */
    public void setPriceWaveSwich(Boolean priceWaveSwich) {
        this.priceWaveSwich = priceWaveSwich;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.login_time
     *
     * @return the value of user.login_time
     *
     * @mbg.generated
     */
    public Long getLoginTime() {
        return loginTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.login_time
     *
     * @param loginTime the value for user.login_time
     *
     * @mbg.generated
     */
    public void setLoginTime(Long loginTime) {
        this.loginTime = loginTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.transaction_report_remind_type
     *
     * @return the value of user.transaction_report_remind_type
     *
     * @mbg.generated
     */
    public Integer getTransactionReportRemindType() {
        return transactionReportRemindType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.transaction_report_remind_type
     *
     * @param transactionReportRemindType the value for user.transaction_report_remind_type
     *
     * @mbg.generated
     */
    public void setTransactionReportRemindType(Integer transactionReportRemindType) {
        this.transactionReportRemindType = transactionReportRemindType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.hasMarketIndex
     *
     * @return the value of user.hasMarketIndex
     *
     * @mbg.generated
     */
    public String getHasmarketindex() {
        return hasmarketindex;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.hasMarketIndex
     *
     * @param hasmarketindex the value for user.hasMarketIndex
     *
     * @mbg.generated
     */
    public void setHasmarketindex(String hasmarketindex) {
        this.hasmarketindex = hasmarketindex == null ? null : hasmarketindex.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.invite_code_discount_count_all
     *
     * @return the value of user.invite_code_discount_count_all
     *
     * @mbg.generated
     */
    public Integer getInviteCodeDiscountCountAll() {
        return inviteCodeDiscountCountAll;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.invite_code_discount_count_all
     *
     * @param inviteCodeDiscountCountAll the value for user.invite_code_discount_count_all
     *
     * @mbg.generated
     */
    public void setInviteCodeDiscountCountAll(Integer inviteCodeDiscountCountAll) {
        this.inviteCodeDiscountCountAll = inviteCodeDiscountCountAll;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.invite_code_discount_count_use
     *
     * @return the value of user.invite_code_discount_count_use
     *
     * @mbg.generated
     */
    public Integer getInviteCodeDiscountCountUse() {
        return inviteCodeDiscountCountUse;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.invite_code_discount_count_use
     *
     * @param inviteCodeDiscountCountUse the value for user.invite_code_discount_count_use
     *
     * @mbg.generated
     */
    public void setInviteCodeDiscountCountUse(Integer inviteCodeDiscountCountUse) {
        this.inviteCodeDiscountCountUse = inviteCodeDiscountCountUse;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.lucky_draw_count
     *
     * @return the value of user.lucky_draw_count
     *
     * @mbg.generated
     */
    public Integer getLuckyDrawCount() {
        return luckyDrawCount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.lucky_draw_count
     *
     * @param luckyDrawCount the value for user.lucky_draw_count
     *
     * @mbg.generated
     */
    public void setLuckyDrawCount(Integer luckyDrawCount) {
        this.luckyDrawCount = luckyDrawCount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.breakout_qdisk_type
     *
     * @return the value of user.breakout_qdisk_type
     *
     * @mbg.generated
     */
    public Integer getBreakoutQdiskType() {
        return breakoutQdiskType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.breakout_qdisk_type
     *
     * @param breakoutQdiskType the value for user.breakout_qdisk_type
     *
     * @mbg.generated
     */
    public void setBreakoutQdiskType(Integer breakoutQdiskType) {
        this.breakoutQdiskType = breakoutQdiskType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.stock_begin_type
     *
     * @return the value of user.stock_begin_type
     *
     * @mbg.generated
     */
    public Integer getStockBeginType() {
        return stockBeginType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.stock_begin_type
     *
     * @param stockBeginType the value for user.stock_begin_type
     *
     * @mbg.generated
     */
    public void setStockBeginType(Integer stockBeginType) {
        this.stockBeginType = stockBeginType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.is_firm_offer_type
     *
     * @return the value of user.is_firm_offer_type
     *
     * @mbg.generated
     */
    public Integer getIsFirmOfferType() {
        return isFirmOfferType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.is_firm_offer_type
     *
     * @param isFirmOfferType the value for user.is_firm_offer_type
     *
     * @mbg.generated
     */
    public void setIsFirmOfferType(Integer isFirmOfferType) {
        this.isFirmOfferType = isFirmOfferType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.sign_in_days
     *
     * @return the value of user.sign_in_days
     *
     * @mbg.generated
     */
    public Integer getSignInDays() {
        return signInDays;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.sign_in_days
     *
     * @param signInDays the value for user.sign_in_days
     *
     * @mbg.generated
     */
    public void setSignInDays(Integer signInDays) {
        this.signInDays = signInDays;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.is_half_stock_type
     *
     * @return the value of user.is_half_stock_type
     *
     * @mbg.generated
     */
    public Integer getIsHalfStockType() {
        return isHalfStockType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.is_half_stock_type
     *
     * @param isHalfStockType the value for user.is_half_stock_type
     *
     * @mbg.generated
     */
    public void setIsHalfStockType(Integer isHalfStockType) {
        this.isHalfStockType = isHalfStockType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.is_start_stock_type
     *
     * @return the value of user.is_start_stock_type
     *
     * @mbg.generated
     */
    public Integer getIsStartStockType() {
        return isStartStockType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.is_start_stock_type
     *
     * @param isStartStockType the value for user.is_start_stock_type
     *
     * @mbg.generated
     */
    public void setIsStartStockType(Integer isStartStockType) {
        this.isStartStockType = isStartStockType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.area_code
     *
     * @return the value of user.area_code
     *
     * @mbg.generated
     */
    public String getAreaCode() {
        return areaCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.area_code
     *
     * @param areaCode the value for user.area_code
     *
     * @mbg.generated
     */
    public void setAreaCode(String areaCode) {
        this.areaCode = areaCode == null ? null : areaCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.call_count
     *
     * @return the value of user.call_count
     *
     * @mbg.generated
     */
    public Integer getCallCount() {
        return callCount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.call_count
     *
     * @param callCount the value for user.call_count
     *
     * @mbg.generated
     */
    public void setCallCount(Integer callCount) {
        this.callCount = callCount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.okex_api_status
     *
     * @return the value of user.okex_api_status
     *
     * @mbg.generated
     */
    public Boolean getOkexApiStatus() {
        return okexApiStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.okex_api_status
     *
     * @param okexApiStatus the value for user.okex_api_status
     *
     * @mbg.generated
     */
    public void setOkexApiStatus(Boolean okexApiStatus) {
        this.okexApiStatus = okexApiStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.bitmex_api_status
     *
     * @return the value of user.bitmex_api_status
     *
     * @mbg.generated
     */
    public Boolean getBitmexApiStatus() {
        return bitmexApiStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.bitmex_api_status
     *
     * @param bitmexApiStatus the value for user.bitmex_api_status
     *
     * @mbg.generated
     */
    public void setBitmexApiStatus(Boolean bitmexApiStatus) {
        this.bitmexApiStatus = bitmexApiStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.is_big_v
     *
     * @return the value of user.is_big_v
     *
     * @mbg.generated
     */
    public Boolean getIsBigV() {
        return isBigV;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.is_big_v
     *
     * @param isBigV the value for user.is_big_v
     *
     * @mbg.generated
     */
    public void setIsBigV(Boolean isBigV) {
        this.isBigV = isBigV;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.leader_id
     *
     * @return the value of user.leader_id
     *
     * @mbg.generated
     */
    public Long getLeaderId() {
        return leaderId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.leader_id
     *
     * @param leaderId the value for user.leader_id
     *
     * @mbg.generated
     */
    public void setLeaderId(Long leaderId) {
        this.leaderId = leaderId;
    }
}